"""add api key reset tokens table and moderation actions

Revision ID: 1685273735b8
Revises: e990b46fbe2b
Create Date: 2026-03-02 21:36:14.712325

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1685273735b8"
down_revision: Union[str, Sequence[str], None] = "e990b46fbe2b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Add new moderation_action enum values (uppercase = PostgreSQL enum name)
    op.execute(
        "ALTER TYPE moderation_action ADD VALUE IF NOT EXISTS 'API_KEY_RESET_REQUESTED'"
    )
    op.execute(
        "ALTER TYPE moderation_action ADD VALUE IF NOT EXISTS 'API_KEY_RESET_COMPLETED'"
    )

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "api_key_reset_tokens",
        sa.Column("token_hash", sa.String(length=128), nullable=False),
        sa.Column("token_prefix", sa.String(length=16), nullable=False),
        sa.Column("agent_id", sa.UUID(), nullable=False),
        sa.Column("is_used", sa.Boolean(), nullable=False),
        sa.Column("used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["agent_id"], ["agents.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_api_key_reset_tokens_agent_id"),
        "api_key_reset_tokens",
        ["agent_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_api_key_reset_tokens_token_hash"),
        "api_key_reset_tokens",
        ["token_hash"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_api_key_reset_tokens_token_hash"), table_name="api_key_reset_tokens"
    )
    op.drop_index(
        op.f("ix_api_key_reset_tokens_agent_id"), table_name="api_key_reset_tokens"
    )
    op.drop_table("api_key_reset_tokens")
    # ### end Alembic commands ###
