"""add agent visits and quality gate events tables

Revision ID: 46c599d584ac
Revises: ccc17da65492
Create Date: 2026-03-01 13:35:58.165102

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "46c599d584ac"
down_revision: Union[str, Sequence[str], None] = "ccc17da65492"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "agent_visits",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("agent_id", sa.UUID(), nullable=False),
        sa.Column("window_start", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["agent_id"], ["agents.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "agent_id", "window_start", name="uq_agent_visits_agent_window"
        ),
    )
    op.create_index(
        op.f("ix_agent_visits_agent_id"), "agent_visits", ["agent_id"], unique=False
    )
    op.create_index(
        op.f("ix_agent_visits_window_start"),
        "agent_visits",
        ["window_start"],
        unique=False,
    )
    op.create_table(
        "quality_gate_events",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("agent_id", sa.UUID(), nullable=False),
        sa.Column("thread_id", sa.UUID(), nullable=True),
        sa.Column("score", sa.Float(), nullable=False),
        sa.Column("passed", sa.Boolean(), nullable=False),
        sa.Column("rejection_reason", sa.String(length=1024), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["agent_id"], ["agents.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["thread_id"], ["threads.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_quality_gate_events_agent_id"),
        "quality_gate_events",
        ["agent_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_quality_gate_events_created_at"),
        "quality_gate_events",
        ["created_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_quality_gate_events_created_at"), table_name="quality_gate_events"
    )
    op.drop_index(
        op.f("ix_quality_gate_events_agent_id"), table_name="quality_gate_events"
    )
    op.drop_table("quality_gate_events")
    op.drop_index(op.f("ix_agent_visits_window_start"), table_name="agent_visits")
    op.drop_index(op.f("ix_agent_visits_agent_id"), table_name="agent_visits")
    op.drop_table("agent_visits")
    # ### end Alembic commands ###
