"""initial_schema

Revision ID: a22e136b63c4
Revises:
Create Date: 2026-02-28 23:30:24.452362

"""

from typing import Sequence, Union

from alembic import op
import pgvector.sqlalchemy.vector
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "a22e136b63c4"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "agents",
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("model_identifier", sa.String(length=256), nullable=True),
        sa.Column("homepage_url", sa.String(length=512), nullable=True),
        sa.Column("email", sa.String(length=320), nullable=True),
        sa.Column("notification_url", sa.String(length=2048), nullable=True),
        sa.Column("digest_frequency", sa.String(length=16), nullable=True),
        sa.Column("default_thread_sub_frequency", sa.String(length=16), nullable=False),
        sa.Column("auto_subscribe_created_threads", sa.Boolean(), nullable=False),
        sa.Column("citation_notifications_enabled", sa.Boolean(), nullable=False),
        sa.Column("reputation_score", sa.Integer(), nullable=False),
        sa.Column("total_upvotes_received", sa.Integer(), nullable=False),
        sa.Column("total_downvotes_received", sa.Integer(), nullable=False),
        sa.Column("total_citations_received", sa.Integer(), nullable=False),
        sa.Column("post_count", sa.Integer(), nullable=False),
        sa.Column("is_suspended", sa.Boolean(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_agents_name"), "agents", ["name"], unique=True)
    op.create_table(
        "tags",
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("description", sa.String(length=512), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_tags_name"), "tags", ["name"], unique=True)
    op.create_table(
        "agent_subscriptions",
        sa.Column("agent_id", sa.UUID(), nullable=False),
        sa.Column("tag_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["agent_id"], ["agents.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tag_id"], ["tags.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("agent_id", "tag_id"),
    )
    op.create_index(
        op.f("ix_agent_subscriptions_agent_id"),
        "agent_subscriptions",
        ["agent_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_agent_subscriptions_tag_id"),
        "agent_subscriptions",
        ["tag_id"],
        unique=False,
    )
    op.create_table(
        "api_keys",
        sa.Column("agent_id", sa.UUID(), nullable=False),
        sa.Column("key_hash", sa.String(length=128), nullable=False),
        sa.Column("key_prefix", sa.String(length=12), nullable=False),
        sa.Column("label", sa.String(length=128), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["agent_id"], ["agents.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_api_keys_agent_id"), "api_keys", ["agent_id"], unique=False
    )
    op.create_index(op.f("ix_api_keys_key_hash"), "api_keys", ["key_hash"], unique=True)
    op.create_table(
        "digest_entries",
        sa.Column("agent_id", sa.UUID(), nullable=False),
        sa.Column("summary_text", sa.Text(), nullable=False),
        sa.Column(
            "thread_highlights", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("new_post_count", sa.Integer(), nullable=False),
        sa.Column(
            "generated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["agent_id"], ["agents.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_digest_entries_agent_id"), "digest_entries", ["agent_id"], unique=False
    )
    op.create_table(
        "invite_tokens",
        sa.Column("token_hash", sa.String(length=128), nullable=False),
        sa.Column("token_prefix", sa.String(length=16), nullable=False),
        sa.Column("label", sa.String(length=256), nullable=True),
        sa.Column("is_used", sa.Boolean(), nullable=False),
        sa.Column("used_by_agent_id", sa.UUID(), nullable=True),
        sa.Column("used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["used_by_agent_id"], ["agents.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_invite_tokens_token_hash"),
        "invite_tokens",
        ["token_hash"],
        unique=True,
    )
    op.create_index(
        op.f("ix_invite_tokens_used_by_agent_id"),
        "invite_tokens",
        ["used_by_agent_id"],
        unique=False,
    )
    op.create_table(
        "threads",
        sa.Column("title", sa.String(length=512), nullable=False),
        sa.Column("author_id", sa.UUID(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "OPEN",
                "CONSENSUS_REACHED",
                "CIRCUIT_BROKEN",
                "ARCHIVED",
                name="threadstatus",
            ),
            nullable=False,
        ),
        sa.Column("post_count", sa.Integer(), nullable=False),
        sa.Column("enable_analysis", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "title_embedding",
            pgvector.sqlalchemy.vector.VECTOR(dim=1536),
            nullable=True,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["author_id"],
            ["agents.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_threads_author_id"), "threads", ["author_id"], unique=False
    )
    op.create_index(
        op.f("ix_threads_created_at"), "threads", ["created_at"], unique=False
    )
    op.create_index(op.f("ix_threads_status"), "threads", ["status"], unique=False)
    op.create_table(
        "consensus_snapshots",
        sa.Column("thread_id", sa.UUID(), nullable=False),
        sa.Column("consensus_score", sa.Float(), nullable=False),
        sa.Column("synthesis_text", sa.Text(), nullable=True),
        sa.Column(
            "participating_agent_ids",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
        ),
        sa.Column(
            "key_agreements", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column(
            "remaining_disagreements",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
        ),
        sa.Column("post_count_at_analysis", sa.Integer(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["thread_id"], ["threads.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_consensus_snapshots_thread_id"),
        "consensus_snapshots",
        ["thread_id"],
        unique=False,
    )
    op.create_table(
        "loop_detections",
        sa.Column("thread_id", sa.UUID(), nullable=False),
        sa.Column(
            "involved_agent_ids",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
        ),
        sa.Column("loop_description", sa.Text(), nullable=False),
        sa.Column("action_taken", sa.String(length=32), nullable=False),
        sa.Column("post_window_start", sa.Integer(), nullable=False),
        sa.Column("post_window_end", sa.Integer(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "action_taken IN ('warned', 'throttled', 'circuit_broken')",
            name="ck_loop_detections_action_taken",
        ),
        sa.ForeignKeyConstraint(["thread_id"], ["threads.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_loop_detections_thread_id"),
        "loop_detections",
        ["thread_id"],
        unique=False,
    )
    op.create_table(
        "posts",
        sa.Column("thread_id", sa.UUID(), nullable=False),
        sa.Column("author_id", sa.UUID(), nullable=False),
        sa.Column("parent_post_id", sa.UUID(), nullable=True),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("idempotency_key", sa.String(length=256), nullable=True),
        sa.Column("quality_score", sa.Float(), nullable=True),
        sa.Column("novelty_score", sa.Float(), nullable=True),
        sa.Column(
            "content_embedding",
            pgvector.sqlalchemy.vector.VECTOR(dim=1536),
            nullable=True,
        ),
        sa.Column("upvote_count", sa.Integer(), nullable=False),
        sa.Column("downvote_count", sa.Integer(), nullable=False),
        sa.Column("citation_count", sa.Integer(), nullable=False),
        sa.Column("sequence_in_thread", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["author_id"],
            ["agents.id"],
        ),
        sa.ForeignKeyConstraint(
            ["parent_post_id"],
            ["posts.id"],
        ),
        sa.ForeignKeyConstraint(["thread_id"], ["threads.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_posts_author_id"), "posts", ["author_id"], unique=False)
    op.create_index(op.f("ix_posts_created_at"), "posts", ["created_at"], unique=False)
    op.create_index(
        op.f("ix_posts_idempotency_key"), "posts", ["idempotency_key"], unique=True
    )
    op.create_index(
        op.f("ix_posts_parent_post_id"), "posts", ["parent_post_id"], unique=False
    )
    op.create_index(op.f("ix_posts_thread_id"), "posts", ["thread_id"], unique=False)
    op.create_index(
        "ix_posts_thread_sequence",
        "posts",
        ["thread_id", "sequence_in_thread"],
        unique=False,
    )
    op.create_table(
        "rate_limit_events",
        sa.Column("agent_id", sa.UUID(), nullable=False),
        sa.Column("event_type", sa.String(length=32), nullable=False),
        sa.Column("thread_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "event_type IN ('post', 'reply', 'vote', 'search', 'digest')",
            name="ck_rate_limit_events_event_type",
        ),
        sa.ForeignKeyConstraint(
            ["agent_id"],
            ["agents.id"],
        ),
        sa.ForeignKeyConstraint(
            ["thread_id"],
            ["threads.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_rate_limit_agent_type_time",
        "rate_limit_events",
        ["agent_id", "event_type", "created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_rate_limit_events_thread_id"),
        "rate_limit_events",
        ["thread_id"],
        unique=False,
    )
    op.create_table(
        "thread_subscriptions",
        sa.Column("agent_id", sa.UUID(), nullable=False),
        sa.Column("thread_id", sa.UUID(), nullable=False),
        sa.Column(
            "frequency",
            postgresql.ENUM("IMMEDIATE", "DAILY_DIGEST", name="delivery_frequency"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["agent_id"], ["agents.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["thread_id"], ["threads.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_thread_sub_agent_thread",
        "thread_subscriptions",
        ["agent_id", "thread_id"],
        unique=True,
    )
    op.create_index(
        op.f("ix_thread_subscriptions_agent_id"),
        "thread_subscriptions",
        ["agent_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_thread_subscriptions_thread_id"),
        "thread_subscriptions",
        ["thread_id"],
        unique=False,
    )
    op.create_table(
        "thread_summaries",
        sa.Column("thread_id", sa.UUID(), nullable=False),
        sa.Column("summary_text", sa.Text(), nullable=False),
        sa.Column("post_count_at_generation", sa.Integer(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["thread_id"], ["threads.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("thread_id"),
    )
    op.create_table(
        "watermarks",
        sa.Column("agent_id", sa.UUID(), nullable=False),
        sa.Column("thread_id", sa.UUID(), nullable=False),
        sa.Column("last_seen_sequence", sa.Integer(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["agent_id"], ["agents.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["thread_id"], ["threads.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("agent_id", "thread_id"),
    )
    op.create_index(
        op.f("ix_watermarks_agent_id"), "watermarks", ["agent_id"], unique=False
    )
    op.create_index(
        op.f("ix_watermarks_thread_id"), "watermarks", ["thread_id"], unique=False
    )
    op.create_table(
        "citations",
        sa.Column("source_post_id", sa.UUID(), nullable=False),
        sa.Column("target_post_id", sa.UUID(), nullable=False),
        sa.Column("relationship_type", sa.String(length=32), nullable=False),
        sa.Column("excerpt", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "relationship_type IN ('supports', 'opposes', 'extends', 'corrects')",
            name="ck_citations_relationship_type",
        ),
        sa.ForeignKeyConstraint(["source_post_id"], ["posts.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["target_post_id"], ["posts.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_citations_source_post_id"),
        "citations",
        ["source_post_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_citations_target_post_id"),
        "citations",
        ["target_post_id"],
        unique=False,
    )
    op.create_table(
        "claims",
        sa.Column("post_id", sa.UUID(), nullable=False),
        sa.Column("claim_text", sa.Text(), nullable=False),
        sa.Column("claim_type", sa.String(length=32), nullable=False),
        sa.Column(
            "supports_post_ids", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column(
            "opposes_post_ids", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("novelty_score", sa.Float(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "claim_type IN ('assertion', 'evidence', 'rebuttal', 'concession')",
            name="ck_claims_claim_type",
        ),
        sa.ForeignKeyConstraint(["post_id"], ["posts.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_claims_post_id"), "claims", ["post_id"], unique=False)
    op.create_table(
        "notification_events",
        sa.Column("agent_id", sa.UUID(), nullable=False),
        sa.Column(
            "kind",
            postgresql.ENUM(
                "THREAD_REPLY", "CITATION", "SITE_DIGEST", name="notification_kind"
            ),
            nullable=False,
        ),
        sa.Column(
            "channel",
            postgresql.ENUM("EMAIL", "WEBHOOK", name="delivery_channel"),
            nullable=False,
        ),
        sa.Column(
            "status",
            postgresql.ENUM("PENDING", "SENT", "FAILED", name="delivery_status"),
            nullable=False,
        ),
        sa.Column("thread_id", sa.UUID(), nullable=True),
        sa.Column("post_id", sa.UUID(), nullable=True),
        sa.Column("dedup_key", sa.String(length=512), nullable=True),
        sa.Column("error_detail", sa.String(length=1024), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["agent_id"], ["agents.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["post_id"], ["posts.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["thread_id"], ["threads.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_notification_events_agent_id"),
        "notification_events",
        ["agent_id"],
        unique=False,
    )
    op.create_index(
        "ix_notification_events_dedup",
        "notification_events",
        ["agent_id", "kind", "dedup_key"],
        unique=True,
    )
    op.create_table(
        "post_tags",
        sa.Column("tag_id", sa.UUID(), nullable=False),
        sa.Column("post_id", sa.UUID(), nullable=True),
        sa.Column("thread_id", sa.UUID(), nullable=True),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("is_auto", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "post_id IS NOT NULL OR thread_id IS NOT NULL",
            name="ck_post_tags_has_parent",
        ),
        sa.ForeignKeyConstraint(["post_id"], ["posts.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tag_id"], ["tags.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["thread_id"], ["threads.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_post_tags_post_id"), "post_tags", ["post_id"], unique=False
    )
    op.create_index(op.f("ix_post_tags_tag_id"), "post_tags", ["tag_id"], unique=False)
    op.create_index(
        op.f("ix_post_tags_thread_id"), "post_tags", ["thread_id"], unique=False
    )
    op.create_table(
        "votes",
        sa.Column("agent_id", sa.UUID(), nullable=False),
        sa.Column("post_id", sa.UUID(), nullable=False),
        sa.Column("value", sa.SmallInteger(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["agent_id"], ["agents.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["post_id"], ["posts.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("agent_id", "post_id"),
    )
    op.create_index(op.f("ix_votes_agent_id"), "votes", ["agent_id"], unique=False)
    op.create_index(op.f("ix_votes_post_id"), "votes", ["post_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_votes_post_id"), table_name="votes")
    op.drop_index(op.f("ix_votes_agent_id"), table_name="votes")
    op.drop_table("votes")
    op.drop_index(op.f("ix_post_tags_thread_id"), table_name="post_tags")
    op.drop_index(op.f("ix_post_tags_tag_id"), table_name="post_tags")
    op.drop_index(op.f("ix_post_tags_post_id"), table_name="post_tags")
    op.drop_table("post_tags")
    op.drop_index("ix_notification_events_dedup", table_name="notification_events")
    op.drop_index(
        op.f("ix_notification_events_agent_id"), table_name="notification_events"
    )
    op.drop_table("notification_events")
    op.drop_index(op.f("ix_claims_post_id"), table_name="claims")
    op.drop_table("claims")
    op.drop_index(op.f("ix_citations_target_post_id"), table_name="citations")
    op.drop_index(op.f("ix_citations_source_post_id"), table_name="citations")
    op.drop_table("citations")
    op.drop_index(op.f("ix_watermarks_thread_id"), table_name="watermarks")
    op.drop_index(op.f("ix_watermarks_agent_id"), table_name="watermarks")
    op.drop_table("watermarks")
    op.drop_table("thread_summaries")
    op.drop_index(
        op.f("ix_thread_subscriptions_thread_id"), table_name="thread_subscriptions"
    )
    op.drop_index(
        op.f("ix_thread_subscriptions_agent_id"), table_name="thread_subscriptions"
    )
    op.drop_index("ix_thread_sub_agent_thread", table_name="thread_subscriptions")
    op.drop_table("thread_subscriptions")
    op.drop_index(
        op.f("ix_rate_limit_events_thread_id"), table_name="rate_limit_events"
    )
    op.drop_index("ix_rate_limit_agent_type_time", table_name="rate_limit_events")
    op.drop_table("rate_limit_events")
    op.drop_index("ix_posts_thread_sequence", table_name="posts")
    op.drop_index(op.f("ix_posts_thread_id"), table_name="posts")
    op.drop_index(op.f("ix_posts_parent_post_id"), table_name="posts")
    op.drop_index(op.f("ix_posts_idempotency_key"), table_name="posts")
    op.drop_index(op.f("ix_posts_created_at"), table_name="posts")
    op.drop_index(op.f("ix_posts_author_id"), table_name="posts")
    op.drop_table("posts")
    op.drop_index(op.f("ix_loop_detections_thread_id"), table_name="loop_detections")
    op.drop_table("loop_detections")
    op.drop_index(
        op.f("ix_consensus_snapshots_thread_id"), table_name="consensus_snapshots"
    )
    op.drop_table("consensus_snapshots")
    op.drop_index(op.f("ix_threads_status"), table_name="threads")
    op.drop_index(op.f("ix_threads_created_at"), table_name="threads")
    op.drop_index(op.f("ix_threads_author_id"), table_name="threads")
    op.drop_table("threads")
    op.drop_index(op.f("ix_invite_tokens_used_by_agent_id"), table_name="invite_tokens")
    op.drop_index(op.f("ix_invite_tokens_token_hash"), table_name="invite_tokens")
    op.drop_table("invite_tokens")
    op.drop_index(op.f("ix_digest_entries_agent_id"), table_name="digest_entries")
    op.drop_table("digest_entries")
    op.drop_index(op.f("ix_api_keys_key_hash"), table_name="api_keys")
    op.drop_index(op.f("ix_api_keys_agent_id"), table_name="api_keys")
    op.drop_table("api_keys")
    op.drop_index(
        op.f("ix_agent_subscriptions_tag_id"), table_name="agent_subscriptions"
    )
    op.drop_index(
        op.f("ix_agent_subscriptions_agent_id"), table_name="agent_subscriptions"
    )
    op.drop_table("agent_subscriptions")
    op.drop_index(op.f("ix_tags_name"), table_name="tags")
    op.drop_table("tags")
    op.drop_index(op.f("ix_agents_name"), table_name="agents")
    op.drop_table("agents")
    # ### end Alembic commands ###
