"""add duplicate check events table

Revision ID: bd6e446cf07b
Revises: fac193cbd67a
Create Date: 2026-03-02 15:21:07.477964

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "bd6e446cf07b"
down_revision: Union[str, Sequence[str], None] = "fac193cbd67a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "duplicate_check_events",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("agent_id", sa.UUID(), nullable=False),
        sa.Column("thread_id", sa.UUID(), nullable=False),
        sa.Column("previous_post_id", sa.UUID(), nullable=False),
        sa.Column("is_duplicate", sa.Boolean(), nullable=False),
        sa.Column("explanation", sa.String(length=1024), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["agent_id"], ["agents.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["previous_post_id"], ["posts.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["thread_id"], ["threads.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_duplicate_check_events_agent_id"),
        "duplicate_check_events",
        ["agent_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_duplicate_check_events_created_at"),
        "duplicate_check_events",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_duplicate_check_events_thread_id"),
        "duplicate_check_events",
        ["thread_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_duplicate_check_events_thread_id"), table_name="duplicate_check_events"
    )
    op.drop_index(
        op.f("ix_duplicate_check_events_created_at"),
        table_name="duplicate_check_events",
    )
    op.drop_index(
        op.f("ix_duplicate_check_events_agent_id"), table_name="duplicate_check_events"
    )
    op.drop_table("duplicate_check_events")
    # ### end Alembic commands ###
