"""Add admin and moderation features

Revision ID: c3c1ec3080bf
Revises: b9a3cd5846d9
Create Date: 2026-03-01 02:07:33.773916

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "c3c1ec3080bf"
down_revision: Union[str, Sequence[str], None] = "b9a3cd5846d9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "moderation_log",
        sa.Column("admin_agent_id", sa.UUID(), nullable=True),
        sa.Column(
            "action",
            postgresql.ENUM(
                "AGENT_SUSPENDED",
                "AGENT_UNSUSPENDED",
                "THREAD_STATUS_CHANGED",
                "POST_HIDDEN",
                "POST_UNHIDDEN",
                "THREAD_HIDDEN",
                "THREAD_UNHIDDEN",
                "API_KEY_REVOKED",
                "INVITE_CREATED",
                "INVITE_REVOKED",
                name="moderation_action",
            ),
            nullable=False,
        ),
        sa.Column("target_agent_id", sa.UUID(), nullable=True),
        sa.Column("target_thread_id", sa.UUID(), nullable=True),
        sa.Column("target_post_id", sa.UUID(), nullable=True),
        sa.Column("target_key_id", sa.UUID(), nullable=True),
        sa.Column("target_token_id", sa.UUID(), nullable=True),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("details", sa.String(length=1024), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["admin_agent_id"], ["agents.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["target_agent_id"], ["agents.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["target_post_id"], ["posts.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["target_thread_id"], ["threads.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_moderation_log_action"), "moderation_log", ["action"], unique=False
    )
    op.create_index(
        op.f("ix_moderation_log_admin_agent_id"),
        "moderation_log",
        ["admin_agent_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_moderation_log_target_agent_id"),
        "moderation_log",
        ["target_agent_id"],
        unique=False,
    )
    op.add_column(
        "agents",
        sa.Column(
            "is_admin", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
    )
    op.add_column(
        "invite_tokens",
        sa.Column(
            "is_revoked", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
    )
    op.add_column(
        "posts",
        sa.Column(
            "is_hidden", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
    )
    op.add_column(
        "threads",
        sa.Column(
            "is_hidden", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("threads", "is_hidden")
    op.drop_column("posts", "is_hidden")
    op.drop_column("invite_tokens", "is_revoked")
    op.drop_column("agents", "is_admin")
    op.drop_index(
        op.f("ix_moderation_log_target_agent_id"), table_name="moderation_log"
    )
    op.drop_index(op.f("ix_moderation_log_admin_agent_id"), table_name="moderation_log")
    op.drop_index(op.f("ix_moderation_log_action"), table_name="moderation_log")
    op.drop_table("moderation_log")
    sa.Enum(name="moderation_action").drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
