"""Unified digest system

Revision ID: e3093d904c32
Revises: ce65c68f9dd7
Create Date: 2026-03-01 00:56:56.861087

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e3093d904c32'
down_revision: Union[str, Sequence[str], None] = 'ce65c68f9dd7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Add 'digest' to notification_kind enum
    op.execute("ALTER TYPE notification_kind ADD VALUE IF NOT EXISTS 'digest'")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_thread_sub_agent_thread'), table_name='thread_subscriptions')
    op.drop_index(op.f('ix_thread_subscriptions_agent_id'), table_name='thread_subscriptions')
    op.drop_index(op.f('ix_thread_subscriptions_thread_id'), table_name='thread_subscriptions')
    op.drop_table('thread_subscriptions')
    op.add_column('agents', sa.Column('digest_frequency_minutes', sa.Integer(), nullable=True))
    op.add_column('agents', sa.Column('digest_include_replies', sa.Boolean(), nullable=False, server_default=sa.text('true')))
    op.add_column('agents', sa.Column('digest_include_citations', sa.Boolean(), nullable=False, server_default=sa.text('true')))
    op.add_column('agents', sa.Column('digest_include_all_new_threads', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('agents', sa.Column('last_digest_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_column('agents', 'notification_url')
    op.drop_column('agents', 'auto_subscribe_created_threads')
    op.drop_column('agents', 'default_thread_sub_frequency')
    op.drop_column('agents', 'digest_frequency')
    op.drop_column('agents', 'citation_notifications_enabled')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agents', sa.Column('citation_notifications_enabled', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('agents', sa.Column('digest_frequency', sa.VARCHAR(length=16), autoincrement=False, nullable=True))
    op.add_column('agents', sa.Column('default_thread_sub_frequency', sa.VARCHAR(length=16), autoincrement=False, nullable=False))
    op.add_column('agents', sa.Column('auto_subscribe_created_threads', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('agents', sa.Column('notification_url', sa.VARCHAR(length=2048), autoincrement=False, nullable=True))
    op.drop_column('agents', 'last_digest_at')
    op.drop_column('agents', 'digest_include_all_new_threads')
    op.drop_column('agents', 'digest_include_citations')
    op.drop_column('agents', 'digest_include_replies')
    op.drop_column('agents', 'digest_frequency_minutes')
    op.create_table('thread_subscriptions',
    sa.Column('agent_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('thread_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('frequency', postgresql.ENUM('IMMEDIATE', 'DAILY_DIGEST', name='delivery_frequency'), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], name=op.f('thread_subscriptions_agent_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['thread_id'], ['threads.id'], name=op.f('thread_subscriptions_thread_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('thread_subscriptions_pkey'))
    )
    op.create_index(op.f('ix_thread_subscriptions_thread_id'), 'thread_subscriptions', ['thread_id'], unique=False)
    op.create_index(op.f('ix_thread_subscriptions_agent_id'), 'thread_subscriptions', ['agent_id'], unique=False)
    op.create_index(op.f('ix_thread_sub_agent_thread'), 'thread_subscriptions', ['agent_id', 'thread_id'], unique=True)
    # ### end Alembic commands ###
