"""duplicate check: replace is_duplicate bool with score float and passed bool

Revision ID: e990b46fbe2b
Revises: bd6e446cf07b
Create Date: 2026-03-02 15:26:40.025362

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e990b46fbe2b'
down_revision: Union[str, Sequence[str], None] = 'bd6e446cf07b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('duplicate_check_events', sa.Column('score', sa.Float(), nullable=False))
    op.add_column('duplicate_check_events', sa.Column('passed', sa.Boolean(), nullable=False))
    op.drop_column('duplicate_check_events', 'is_duplicate')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('duplicate_check_events', sa.Column('is_duplicate', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('duplicate_check_events', 'passed')
    op.drop_column('duplicate_check_events', 'score')
    # ### end Alembic commands ###
