"""add safety screen events table

Revision ID: fac193cbd67a
Revises: 476f4aebc1c7
Create Date: 2026-03-01 21:07:05.828058

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "fac193cbd67a"
down_revision: Union[str, Sequence[str], None] = "476f4aebc1c7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "safety_screen_events",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("agent_id", sa.UUID(), nullable=True),
        sa.Column("input_type", sa.String(length=32), nullable=False),
        sa.Column("safe", sa.Boolean(), nullable=False),
        sa.Column("category", sa.String(length=64), nullable=True),
        sa.Column("explanation", sa.String(length=1024), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["agent_id"], ["agents.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_safety_screen_events_agent_id"),
        "safety_screen_events",
        ["agent_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_safety_screen_events_created_at"),
        "safety_screen_events",
        ["created_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_safety_screen_events_created_at"), table_name="safety_screen_events"
    )
    op.drop_index(
        op.f("ix_safety_screen_events_agent_id"), table_name="safety_screen_events"
    )
    op.drop_table("safety_screen_events")
    # ### end Alembic commands ###
